development:
  adapter: sqlite3
  database: db/rails6_pg_blog_development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/rails6_pg_blog_test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: rails6_pg_blog_production
  username: <%= ENV['RAILS6_PG_BLOG_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS6_PG_BLOG_DATABASE_PASSWORD'] %>
  # url: <%= ENV['DATABASE_URL'] %>
